apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: aws-mcp-http-toolhive
  namespace: mcp-servers
spec:
  image: image-registry.openshift-image-registry.svc:5000/mcp-servers/aws-api-mcp-server
  transport: streamable-http
  port: 8000
  targetPort: 8000
  permissionProfile:
    type: builtin
    name: network
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
  # Reference secrets here
  secrets:
    - name: aws-credentials
      key: access-key-id
      targetEnvName: AWS_ACCESS_KEY_ID
    - name: aws-credentials
      key: secret-access-key
      targetEnvName: AWS_SECRET_ACCESS_KEY      
  env:
    - name: AWS_REGION
      value: "us-east-1"
    - name: AWS_API_MCP_TRANSPORT
      value: "streamable-http"
    - name: AWS_API_MCP_HOST
      value: "0.0.0.0"
    - name: AWS_API_MCP_PORT
      value: "8000"
    - name: AWS_API_MCP_ALLOWED_HOSTS
      value: "*"
    - name: AWS_API_MCP_ALLOWED_ORIGINS
      value: "*"
    - name: AUTH_TYPE
      value: "no-auth"
    # Working Directory
    - name: AWS_API_MCP_WORKING_DIR
      value: "/tmp/aws-api-mcp/workdir"
    # CRITICAL: Point HOME to writable directory
    - name: HOME
      value: "/tmp"
    - name: TMPDIR
      value: "/tmp"
    - name: XDG_RUNTIME_DIR
      value: "/tmp"
    - name: XDG_CACHE_HOME
      value: "/tmp/.cache"
    - name: XDG_CONFIG_HOME
      value: "/tmp/.config"
    - name: XDG_DATA_HOME
      value: "/tmp/.local/share"
    # Optional: Disable telemetry if needed
    - name: AWS_API_MCP_TELEMETRY
      value: "false"
  podTemplateSpec:
    spec:
      serviceAccountName: azure-mcp-server-toolhive-sa
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
        - name: mcp
          image: image-registry.openshift-image-registry.svc:5000/mcp-servers/aws-api-mcp-server
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          volumeMounts:
            - name: cache
              mountPath: /tmp/cache
      volumes:
        - name: cache
          emptyDir: {}