apiVersion: toolhive.stacklok.dev/v1alpha1
kind: MCPServer
metadata:
  name: netbox-mcp-http-toolhive
  namespace: mcp-servers
spec:
  image: image-registry.openshift-image-registry.svc:5000/mcp-servers/netbox-mcp-server-http
  transport: streamable-http
  port: 8080
  targetPort: 8080
  permissionProfile:
    type: builtin
    name: network
  oidcConfig:
    type: inline
    resourceUrl: http://netbox-mcp-http-toolhive-auth-mcp-servers.apps.rhocp-cluster.presidiolab.local/mcp
    inline:
      issuer: https://presidio-mcp.us.auth0.com/
      jwksUrl: https://presidio-mcp.us.auth0.com/.well-known/jwks.json
      audience: infragenie-mcp
      clientId: 7mnEmIdqSJ6iZpUMq1rwTkNdHs0gPNhN
      clientSecretRef:
        name: auth0-oidc-credentials
        key: client-secret
  resources:
    limits:
      cpu: "100m"
      memory: "128Mi"
    requests:
      cpu: "50m"
      memory: "64Mi"
